name: workflow

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
            - name: Welcome message
              run: echo "first job in git"

            - name: List files
              run: ls

            - name: Read file
              run: cat acts